### PR TITLE
"Hi, this is a reverted pull request to show added popup effects!"

### PR DESCRIPTION
**Pull request by CrystallineButterfly**
Hi there, 

Hope you are having a great day!

This is a reverted pull request to show I have completed the Popup containers for each "project example";
The reason it is reverted is that the work me and my coding partner did, with commits at each stage of completion, was made on the "buttonjs" branch, therefore I made a mistake when merging it, so I have to revert it to show you our progress via commit history. 

All the best- K

Reverts CrystallineButterfly/CrystallineButterfly.porfolio#13

### CODE REVIEW

**Review by AnselemOdims — COMMENTED** [review]
# Invalid Request 🛑 
You have been doing very good work on this project but unfortunately I can not proceed with the review as there are some discrepancies. Check below for details.

- Kindly setup linter checks for Javascript(ESlint)

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by AnselemOdims** [comment]
Kindly check [here](https://github.com/microverseinc/linters-config) to see how it can be configured

**Comment by CrystallineButterfly** [comment]
Hi @AnselemOdims I do have this already installed in my VS code, so if I run=

npm install --save-dev eslint@7.x eslint-config-airbnb-base@14.x eslint-plugin-import@2.x babel-eslint@10.x`

Again, will it work in my github also?

**Comment by CrystallineButterfly** [comment]
Hi, @AnselemOdims So installing again doesn't work as it is already in there, so I'm unsure why it shows I don't have it as I have used it during the whole project, it must just not be connected to my Github for some reason, pls help!

Thank you for your help-K

**Review by topeogunleye — COMMENTED** [review]
Hi @CrystallineButterfly, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a pair programming project with no contributions from your partner. Kindly make sure that your partner makes contributions to your project.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

**Comment by CrystallineButterfly** [comment]
Hi @topeogunleye 
Thank you for the review, however, pls go to reverts #13, link at top of the page here in the first message; in there you will see the commits from my coding partner! 

And ok @m05e5 I will do it now! And submit again, thank you! 

All the best-K

**Comment by topeogunleye** [comment]
> Hi @topeogunleye Thank you for the review, however, pls go to reverts #13, link at top of the page here in the first message; in there you will see the commits from my coding partner!
> 
> And ok @m05e5 I will do it now! And submit again, thank you!
> 
> All the best-K

@CrystallineButterfly , You also haven't implemented the pop-up modal as required by the project requirements.  please do so

**Comment by CrystallineButterfly** [comment]
Hi @topeogunleye Pls, specify what you mean precisely? I am sure my project already meets the requirements, and what you are suggesting has not been pointed out by the 2 other code reviewers. 

I would love a clearer explanation. 

All the best- K

**Comment by topeogunleye** [comment]
> Hi @topeogunleye Pls, specify what you mean precisely? I am sure my project already meets the requirements, and what you are suggesting has not been pointed out by the 2 other code reviewers.
> 
> I would love a clearer explanation.
> 
> All the best- K

@CrystallineButterfly The Review you submitted this pull request for is Pop Up Details and you haven't implemented the Pop up details modal yet

**Comment by CrystallineButterfly** [comment]
Hi @topeogunleye Everything is in there so I am unsure where you are looking, the popup js/html/css is fully complete.

**Comment by CrystallineButterfly** [comment]
Hi @topeogunleye Pls read this pull request info from the start, everything is there, this pull request however is a revert from buttonjs, as the commits made for everything are in the #13 as mentioned at the start of this pull request, kindly have a look in #13 which is where everything has been done! 

Thank you-K

**Comment by topeogunleye** [comment]
> Hi @topeogunleye Everything is in there so I am unsure where you are looking, the popup js/html/css is fully complete.

In this pull request, there is no pop up modal

**Comment by topeogunleye** [comment]
> Hi @topeogunleye Pls read this pull request info from the start, everything is there, this pull request however is a revert from buttonjs, as the commits made for everything are in the #13 as mentioned at the start of this pull request, kindly have a look in #13 which is where everything has been done!
> 
> Thank you-K

I can only make a review on the PR you submitted, and also you previous pull request does not have Eslint setup. Please get your[ linters ](https://github.com/microverseinc/linters-config/tree/master/html-css-js)for JavaScript projects and set it up

**Comment by topeogunleye** [comment]
> Hi there @topeogunleye Thank you for your response, however as mentioned, I had to revert the original PR as I merged it accidentally, which was my mistake, so, therefore, I reverted it and you can access it here #13 As this one has all the commit history, etc, and I also have used ESLINT in all JS projects so far so I am confused as to why it is not showing up on my Git-hub, I will try and solve this and send again. And do you suggest I ask my coding partner to submit more commits on another branch? Before I do the next PR?

Yes, please your coding partner should have more commits for your new branch for your `Pop up modal details` feature. Kindly update your linters.yml file in your `.github/workflows` folder if you want ESLint checks to show up on GitHub.

**Comment by CrystallineButterfly** [comment]
Ok @topeogunleye Thank you bro!

**Pull request merged**
