### PR TITLE
Hi, This is a pull request to deploy this portfolio on Github pages!

### PR DESCRIPTION
**Pull request by CrystallineButterfly**
Hello there, 

I hope you are having a great day!

This pull request is to enable GitHub pages, and I have also made a few fixes, typos and code cleaned up.

I look forward to hearing from you. 

All the best- K

### CODE REVIEW

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @CrystallineButterfly, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

768070f3-bc9a-4aba-b8bc-25793e00ea1e_text

## Highlights
✔️ Great job so far on deploying the project.

## Required 
- [x] Kindly update your readme by adding a link to the live version.
- [ ] Kindly make sure that your live version works correctly, right now images in the live version are broken and background images are not displayed as well.

https://user-images.githubusercontent.com/70269507/166207798-b2409674-fd23-4ab9-99fd-97e2cf7f88b5.mov

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by CrystallineButterfly** [comment]
Hi, @sja-thedude Thank you, I have added the live-demo link in my README.md file and I will also make the other suggested changes! 

However, I am unsure why my live demo is not displaying my images correctly, please can you point me in the right direction for this fix? 

All the best-K

**Comment by CrystallineButterfly** [comment]
Hi @sja-thedude So I have checked my images and they are all good, on my live version directly from VS code, they are working perfectly, so I am unsure why on my live demo via pages, they aren't working! 

If you have any suggestions, thank you.

**Comment by sja-thedude** [comment]
> Hi @sja-thedude So I have checked my images and they are all good, on my live version directly from VS code, they are working perfectly, so I am unsure why on my live demo via pages, they aren't working!
> 
> If you have any suggestions, thank you.

Hi @CrystallineButterfly You can try to delete the deployment and again deploy in order for the portfolio live version to work or you can deploy directly to the main branch and add a live link to the readme which is fine too.

**Comment by CrystallineButterfly** [comment]
Hi there @sja-thedude So I have added the README live demo link, successfully: and attempted to re-deployed to fix the images, but it still has not worked, I am unsure why, as they are working perfectly fine on my VS code live version. 

I also attempted to deploy from a different branch to see if that was the issue, but no luck there either. 

If I re-submit for code review, do you think the next code reviewer will accept given our discussion in this thread? 

As I feel it may be an issue with GitHub and not with my code. 

All the best-K

**Comment by sja-thedude** [comment]
> Hi there @sja-thedude So I have added the README live demo link, successfully: and attempted to re-deploy to fix the images, but it still has not worked, I am unsure why, as they are working perfectly fine on my VS code live version. 
> 
> 
> 
> I also attempted to deploy from a different branch to see if that was the issue, but no luck there either. 
> 
> 
> 
> If I re-submit for code review, do you think the next code reviewer will accept given our discussion in this thread? 
> 
> 
> 
> As I feel it may be an issue with GitHub and not with my code. 
> 
> 
> 
> All the best-K

Hi @CrystallineButterfly Can you try adding a dot before importing images! I think it will work!

**Comment by CrystallineButterfly** [comment]
Hi @sja-thedude Thank you for the suggestion, I have just done it, and will check now!

**Comment by CrystallineButterfly** [comment]
Hi @sja-thedude So it seems to have worked on some images but not all, any more suggestions? ahaha!

**Comment by CrystallineButterfly** [comment]
Hi, @sja-thedude Thank you very much! It has now worked! I will submit it again and thank you again for teaching me this fix!

All the best-K

**Review by thecodechaser — APPROVED** [review]
## STATUS: APPROVED 🟢

## Hi @CrystallineButterfly👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by CrystallineButterfly** [comment]
Hi, @thecodechaser Thank you very much for the awesome code review! 

giphy

Blessings to you, 
All the best-k

**Comment by thecodechaser** [comment]
@CrystallineButterfly, Good luck with upcoming projects 😄

**Pull request merged**
